apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: ingress-demo
  namespace: default
spec:
  ports:
  - nodePort: 31800
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp
  type: LoadBalancer
